/**
 * lib/chartSource.ts
 *
 * Reusable chart source registry.
 * To add a new regional chart in future:
 *   1. Run: scripts/build-regional-charts.mjs (add your playlist to the PLAYLISTS array)
 *   2. Import the generated data file here
 *   3. Add a new ChartSource entry to CHART_SOURCES
 *   No UI code changes required.
 */

import { SongNode, Vibe } from './types';
import { teluguChartData } from './teluguChartData';
import { tamilChartData }  from './tamilChartData';
import { hindiChartData }  from './hindiChartData';

export interface ChartSource {
  /** Vibe ID — must match the Vibe union type in types.ts */
  id: Vibe;
  /** Display name */
  title: string;
  /** Source Spotify playlist URL (for documentation / rebuild) */
  playlistUrl: string;
  /** ISO 639-1 language code or descriptive label */
  language: string;
  /** Static SongNode[] — generated by build-regional-charts.mjs */
  songs: SongNode[];
}

/**
 * Registry of all playlist-backed chart sources.
 * Keyed by Vibe ID for O(1) lookup.
 */
export const CHART_SOURCES: Partial<Record<Vibe, ChartSource>> = {
  'top-telugu': {
    id:          'top-telugu',
    title:       'Top Telugu',
    playlistUrl: 'https://open.spotify.com/playlist/1llHjtjECBo12ChwOGe38L',
    language:    'te',
    songs:       teluguChartData,
  },
  'top-tamil': {
    id:          'top-tamil',
    title:       'Top Tamil',
    playlistUrl: 'https://open.spotify.com/playlist/5lfuu0un8XjAtUdxwtqjm4',
    language:    'ta',
    songs:       tamilChartData,
  },
  'top-hindi': {
    id:          'top-hindi',
    title:       'Top Hindi',
    playlistUrl: 'https://open.spotify.com/playlist/0i2S0eEdftTrmLKueMWUKX',
    language:    'hi',
    songs:       hindiChartData,
  },
};

/** Returns true if a vibe is backed by a curated playlist. */
export function isPlaylistVibe(vibe: Vibe): boolean {
  return vibe in CHART_SOURCES;
}

/** Returns the static song list for a playlist-backed vibe, or null. */
export function getPlaylistSongs(vibe: Vibe): SongNode[] | null {
  return CHART_SOURCES[vibe]?.songs ?? null;
}
